FROM sonarqube
  
LABEL MAINTAINER="srikant.noorani@broadcom.com"


ENV SQUBE_CONF = /opt/sonarqube/conf \
    SQUBE_DATA = /opt/sonarqube/data \
    SQUBE_LOGS = /opt/sonarqube/logs \
    SQUBE_EXT = /opt/sonarqube/extensions \
    SQUBE = /opt/sonarqube

WORKDIR  ${SQUBE}

EXPOSE 9000
