version: '3'

services:

 jenkins:
    build:
      context: ./jenkins
      dockerfile: $PWD/Dockerfile
    image: jenkins/jenkins
    container_name: jenkins
    environment:
      - JAVA_OPS="-Dhudson.model.DirectoryBrowserSupport.CSP="
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - COMPOSE_DIR/jenkins/jenkins_home:/var/jenkins_home
 
 jfrog:
    build:
      context: ./jfrog
      dockerfile: $PWD/Dockerfile
    image: docker.bintray.io/jfrog/artifactory-oss
    container_name: jfrog
    ports:
      - "8989:8081"
    volumes:
      - COMPOSE_DIR/jfrog/JFROG_RUNTIME/data:/var/opt/jfrog/artifactory

 apm-wv:
    build:
      context: ./apm/WV
      dockerfile: $PWD/Dockerfile
    image: apm-wv:latest
    container_name: apm-wv
    depends_on:
      - apm-em
    ports:
      - "9999:8999"
    volumes:
      - COMPOSE_DIR/apm/WV/WV_RUNTIME/logs:/opt/CA/Introscope/logs

 apm-em:
    build:
      context: ./apm/EM
      dockerfile: $PWD/Dockerfile
    image: apm-em:latest
    container_name: apm-em
    depends_on:
      - apm-db
    ports:
      - "5001:5001"
      - "8091:8081"
      - "8454:8444"
    extra_hosts:
      - "centOS7.5-aop.dev.fco:10.238.238.47"
    volumes:
      - COMPOSE_DIR/apm/EM/EM_RUNTIME/logs:/opt/CA/Introscope/logs 
      - COMPOSE_DIR/apm/EM/EM_RUNTIME/data:/opt/CA/Introscope/data 
      - COMPOSE_DIR/apm/EM/EM_RUNTIME/config:/opt/CA/Introscope/config 


 apm-db:
    build:
      context: ./apm/DB
      dockerfile: $PWD/Dockerfile
    image: apm-db
    container_name: apm-db
    ports:
      - "5444:5432"
    volumes:
      - COMPOSE_DIR/apm/DB/PGDATA:/var/lib/postgresql/data
